# Generated by Django 5.1.1 on 2024-09-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganttapp', '0002_groupsecond_rename_name_group_hangar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group_second',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='hangar',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tail_number',
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='GroupSecond',
        ),
    ]
